/**
 * CourtListener court-id → human-readable name.
 *
 * The litigation corpus stores courts as CourtListener ids (e.g. `ca9`,
 * `mnd`). Those abbreviations are opaque to most users, so the filter UI
 * shows the full name instead (CA9 → "Ninth Circuit Court of Appeals",
 * MND → "District of Minnesota"). Filtering still happens on the id; this
 * map is display-only.
 *
 * Covers every court id present in the corpus as of 2026-06 (109 ids:
 * 13 courts of appeals + 96 district courts). `courtDisplayName` falls back
 * to the upper-cased id for any future id not yet listed here.
 */
export const COURT_NAMES: Record<string, string> = {
  // ── U.S. Courts of Appeals ───────────────────────────────────────────
  ca1: 'First Circuit Court of Appeals',
  ca2: 'Second Circuit Court of Appeals',
  ca3: 'Third Circuit Court of Appeals',
  ca4: 'Fourth Circuit Court of Appeals',
  ca5: 'Fifth Circuit Court of Appeals',
  ca6: 'Sixth Circuit Court of Appeals',
  ca7: 'Seventh Circuit Court of Appeals',
  ca8: 'Eighth Circuit Court of Appeals',
  ca9: 'Ninth Circuit Court of Appeals',
  ca10: 'Tenth Circuit Court of Appeals',
  ca11: 'Eleventh Circuit Court of Appeals',
  cadc: 'D.C. Circuit Court of Appeals',
  cafc: 'Federal Circuit Court of Appeals',

  // ── U.S. District Courts ─────────────────────────────────────────────
  akd: 'District of Alaska',
  almd: 'Middle District of Alabama',
  alnd: 'Northern District of Alabama',
  alsd: 'Southern District of Alabama',
  ared: 'Eastern District of Arkansas',
  arwd: 'Western District of Arkansas',
  azd: 'District of Arizona',
  cacd: 'Central District of California',
  caed: 'Eastern District of California',
  cand: 'Northern District of California',
  casd: 'Southern District of California',
  cod: 'District of Colorado',
  ctd: 'District of Connecticut',
  dcd: 'District of Columbia',
  ded: 'District of Delaware',
  flmd: 'Middle District of Florida',
  flnd: 'Northern District of Florida',
  flsd: 'Southern District of Florida',
  gamd: 'Middle District of Georgia',
  gand: 'Northern District of Georgia',
  gasd: 'Southern District of Georgia',
  gud: 'District of Guam',
  hid: 'District of Hawaii',
  iand: 'Northern District of Iowa',
  iasd: 'Southern District of Iowa',
  idd: 'District of Idaho',
  ilcd: 'Central District of Illinois',
  ilnd: 'Northern District of Illinois',
  ilsd: 'Southern District of Illinois',
  innd: 'Northern District of Indiana',
  insd: 'Southern District of Indiana',
  ksd: 'District of Kansas',
  kyed: 'Eastern District of Kentucky',
  kywd: 'Western District of Kentucky',
  laed: 'Eastern District of Louisiana',
  lamd: 'Middle District of Louisiana',
  lawd: 'Western District of Louisiana',
  mad: 'District of Massachusetts',
  mdd: 'District of Maryland',
  med: 'District of Maine',
  mied: 'Eastern District of Michigan',
  miwd: 'Western District of Michigan',
  mnd: 'District of Minnesota',
  moed: 'Eastern District of Missouri',
  mowd: 'Western District of Missouri',
  msnd: 'Northern District of Mississippi',
  mssd: 'Southern District of Mississippi',
  mtd: 'District of Montana',
  nced: 'Eastern District of North Carolina',
  ncmd: 'Middle District of North Carolina',
  ncwd: 'Western District of North Carolina',
  ndd: 'District of North Dakota',
  ned: 'District of Nebraska',
  nhd: 'District of New Hampshire',
  njd: 'District of New Jersey',
  nmd: 'District of New Mexico',
  nmid: 'District of the Northern Mariana Islands',
  nvd: 'District of Nevada',
  nyed: 'Eastern District of New York',
  nynd: 'Northern District of New York',
  nysd: 'Southern District of New York',
  nywd: 'Western District of New York',
  ohnd: 'Northern District of Ohio',
  ohsd: 'Southern District of Ohio',
  oked: 'Eastern District of Oklahoma',
  oknd: 'Northern District of Oklahoma',
  okwd: 'Western District of Oklahoma',
  ord: 'District of Oregon',
  paed: 'Eastern District of Pennsylvania',
  pamd: 'Middle District of Pennsylvania',
  pawd: 'Western District of Pennsylvania',
  prd: 'District of Puerto Rico',
  rid: 'District of Rhode Island',
  scd: 'District of South Carolina',
  sdd: 'District of South Dakota',
  tned: 'Eastern District of Tennessee',
  tnmd: 'Middle District of Tennessee',
  tnwd: 'Western District of Tennessee',
  txed: 'Eastern District of Texas',
  txnd: 'Northern District of Texas',
  txsd: 'Southern District of Texas',
  txwd: 'Western District of Texas',
  utd: 'District of Utah',
  vaed: 'Eastern District of Virginia',
  vawd: 'Western District of Virginia',
  vid: 'District of the Virgin Islands',
  vtd: 'District of Vermont',
  waed: 'Eastern District of Washington',
  wawd: 'Western District of Washington',
  wied: 'Eastern District of Wisconsin',
  wiwd: 'Western District of Wisconsin',
  wvnd: 'Northern District of West Virginia',
  wvsd: 'Southern District of West Virginia',
  wyd: 'District of Wyoming',
}

/**
 * Display name for a CourtListener court id. Falls back to the upper-cased
 * id when the id isn't in the map (e.g. a court newly synced into the
 * corpus before this map is updated), so the UI never shows a blank.
 */
export function courtDisplayName(code: string): string {
  return COURT_NAMES[code] ?? code.toUpperCase()
}
