import { defineTunables } from '@/tune/registry'

/**
 * The engraved render style's halftone, as knobs. The `value:` of each is the one copy of
 * its default; `styles/engraved/resolve.ts` reads them back, lays a variant's
 * `params.engraved` over them, and whatever is being tuned over that.
 *
 * Ids are `owl.engraved.<name>` and not `owl.design.params.engraved.<name>`: the design's
 * `params` record is empty for the owl as sent, and the flat owl does not carry a style's
 * settings it never reads. The variant's patch key is the same `<name>`.
 *
 * Grouped as the work goes: choose a screen, set its lines, set the tone it prints, set
 * how it holds up small, then the print and the scan finish.
 */

const SELF = 'src/owl/knobs/engraved.ts'

const base = { scope: 'owl', source: { file: SELF } } as const
const SCREEN = { ...base, group: 'Engraving · screen' } as const
const LINES = { ...base, group: 'Engraving · lines' } as const
const TONE = { ...base, group: 'Engraving · tone' } as const
const FORM = { ...base, group: 'Engraving · form' } as const
const PRINT = { ...base, group: 'Engraving · print' } as const
const SMALL = { ...base, group: 'Engraving · small sizes' } as const
const SCAN = { ...base, group: 'Scan finish' } as const

export const owlEngravedKnobs = defineTunables([
  {
    ...SCREEN,
    id: 'owl.engraved.screen',
    label: 'Screen',
    kind: 'select',
    value: 'displaced',
    options: [
      { label: 'Straight lines', value: 'straight' },
      { label: 'Displaced over the form', value: 'displaced' },
      { label: 'Contour lines', value: 'contour' },
      { label: 'Mixed: contours where the form turns', value: 'mixed' },
    ],
    note: 'Straight: parallel lines, weight carries the tone. Displaced: the same lines bent over each shape, as on a banknote. Contour: lines of equal distance from the edge. Mixed: contour on the head, face, belly and body, straight elsewhere.',
  },
  {
    ...SCREEN,
    id: 'owl.engraved.pitch',
    label: 'Line spacing',
    kind: 'number',
    value: 1.5,
    min: 0.6,
    max: 5,
    step: 0.05,
    note: 'Centre to centre, in figure units (the figure is 100 across). Smaller is a finer screen and more path data.',
  },
  {
    ...SCREEN,
    id: 'owl.engraved.angle',
    label: 'Angle',
    kind: 'number',
    value: 78,
    min: -90,
    max: 90,
    step: 1,
    note: 'Degrees from horizontal. 90 is vertical. Each region adds its own turn to this (see Fan).',
  },
  {
    ...SCREEN,
    id: 'owl.engraved.fan',
    label: 'Fan',
    kind: 'number',
    value: 1,
    min: 0,
    max: 1.5,
    step: 0.05,
    note: 'How far the regions turn from the plate’s angle: the head leans, the face and belly cross it, the wings mirror. 0 prints every region at one angle.',
  },
  {
    ...SCREEN,
    id: 'owl.engraved.contourPitch',
    label: 'Contour spacing',
    kind: 'number',
    value: 1.5,
    min: 0.6,
    max: 5,
    step: 0.05,
    note: 'The spacing between contour lines, used by the contour and mixed screens.',
  },

  {
    ...LINES,
    id: 'owl.engraved.wmin',
    label: 'Finest line',
    kind: 'number',
    value: 0.1,
    min: 0,
    max: 1,
    step: 0.01,
    note: 'The weight a line has just above the highlight floor, figure units.',
  },
  {
    ...LINES,
    id: 'owl.engraved.wmax',
    label: 'Heaviest line',
    kind: 'number',
    value: 0.95,
    min: 0.2,
    max: 1.3,
    step: 0.01,
    note: 'As a share of the spacing. Near 1 the darkest lines touch and close up into solid ink; over 1 they overlap.',
  },
  {
    ...LINES,
    id: 'owl.engraved.floor',
    label: 'Highlight floor',
    kind: 'number',
    value: 0.07,
    min: 0,
    max: 0.6,
    step: 0.01,
    note: 'Tone under which nothing prints. Lines taper to a point as they approach it, so highlights open to paper.',
  },
  {
    ...LINES,
    id: 'owl.engraved.breakAt',
    label: 'Break-up below',
    kind: 'number',
    value: 0.22,
    min: 0,
    max: 0.6,
    step: 0.01,
    note: 'Under this tone a line breaks into dashes, then dots, before it vanishes. 0 keeps lines whole.',
  },
  {
    ...LINES,
    id: 'owl.engraved.dash',
    label: 'Dash length',
    kind: 'number',
    value: 3,
    min: 1,
    max: 8,
    step: 0.1,
    note: 'The period of the break-up, in figure units.',
  },
  {
    ...LINES,
    id: 'owl.engraved.hatch',
    label: 'Cross-hatch from tone',
    kind: 'number',
    value: 0.72,
    min: 0.3,
    max: 1,
    step: 0.01,
    note: 'A second screen engages in tones darker than this. 1 turns it off.',
  },
  {
    ...LINES,
    id: 'owl.engraved.hatchAngle',
    label: 'Cross-hatch angle',
    kind: 'number',
    value: 58,
    min: -90,
    max: 90,
    step: 1,
    note: 'Degrees from the main screen.',
  },
  {
    ...LINES,
    id: 'owl.engraved.hatchWeight',
    label: 'Cross-hatch weight',
    kind: 'number',
    value: 0.55,
    min: 0.2,
    max: 1.2,
    step: 0.01,
    note: 'Relative to the main screen’s lines.',
  },
  {
    ...LINES,
    id: 'owl.engraved.waver',
    label: 'Hand wobble',
    kind: 'number',
    value: 0.1,
    min: 0,
    max: 0.8,
    step: 0.01,
    note: 'How far a line wanders from true, figure units. A little is what stops a screen reading as a machine’s.',
  },

  {
    ...TONE,
    id: 'owl.engraved.gamma',
    label: 'Gamma',
    kind: 'number',
    value: 1,
    min: 0.4,
    max: 2.5,
    step: 0.02,
    note: 'Above 1 lightens the mid-tones; below 1 darkens them.',
  },
  {
    ...TONE,
    id: 'owl.engraved.contrast',
    label: 'Contrast',
    kind: 'number',
    value: 1.15,
    min: 0.3,
    max: 3,
    step: 0.02,
    note: 'About the middle grey. More pushes lights to paper and darks to solid.',
  },
  {
    ...TONE,
    id: 'owl.engraved.brightness',
    label: 'Brightness',
    kind: 'number',
    value: 0,
    min: -0.5,
    max: 0.5,
    step: 0.01,
    note: 'Positive prints more ink, negative less.',
  },
  {
    ...TONE,
    id: 'owl.engraved.grain',
    label: 'Tone grain',
    kind: 'number',
    value: 0.08,
    min: 0,
    max: 0.5,
    step: 0.01,
    note: 'A seeded roughness in the tone, so that no two stretches of a line are the same weight.',
  },

  {
    ...FORM,
    id: 'owl.engraved.light',
    label: 'Light direction',
    kind: 'number',
    value: 225,
    min: 0,
    max: 360,
    step: 5,
    note: 'Degrees clockwise from the right. 225 is from the upper left.',
  },
  {
    ...FORM,
    id: 'owl.engraved.model',
    label: 'Modelling',
    kind: 'number',
    value: 1.1,
    min: 0,
    max: 2.5,
    step: 0.05,
    note: 'How much the light turns each shape into volume: lighter on the lit side, heavier on the far side.',
  },
  {
    ...FORM,
    id: 'owl.engraved.edge',
    label: 'Edge darkening',
    kind: 'number',
    value: 0.15,
    min: -0.5,
    max: 1,
    step: 0.01,
    note: 'Extra ink toward each shape’s edge, as the surface turns away. Negative lights the rim.',
  },
  {
    ...FORM,
    id: 'owl.engraved.shadow',
    label: 'Cast shadow',
    kind: 'number',
    value: 0.22,
    min: 0,
    max: 1,
    step: 0.01,
    note: 'Ink under each shape that sits in front of another, away from the light.',
  },
  {
    ...FORM,
    id: 'owl.engraved.displace',
    label: 'Displacement',
    kind: 'number',
    value: 3.2,
    min: 0,
    max: 8,
    step: 0.1,
    note: 'How far the displaced screen’s lines bulge over a shape’s height, figure units.',
  },

  {
    ...PRINT,
    id: 'owl.engraved.keyline',
    label: 'Keyline weight',
    kind: 'number',
    value: 0.5,
    min: 0,
    max: 1.6,
    step: 0.05,
    note: 'The outline round each shape’s visible edge. 0 leaves edges to the lines alone.',
  },
  {
    ...PRINT,
    id: 'owl.engraved.ground',
    label: 'Ground',
    kind: 'select',
    value: 'tint',
    options: [
      { label: 'None: the owl on the page', value: 'none' },
      { label: 'Paper disc', value: 'paper' },
      { label: 'Tinted disc', value: 'tint' },
    ],
    note: 'What the owl stands on: nothing, a plain disc of paper, or a disc with a light screen of its own.',
  },
  {
    ...PRINT,
    id: 'owl.engraved.ink',
    label: 'Ink',
    kind: 'color',
    value: '#17140f',
    note: 'The lines, and with the palette’s rims and pupils, which a variant sets to match.',
  },
  {
    ...PRINT,
    id: 'owl.engraved.paper',
    label: 'Paper',
    kind: 'color',
    value: '#f4eee0',
    note: 'The ground disc and the owl’s lenses.',
  },
  {
    ...PRINT,
    id: 'owl.engraved.fidelity',
    label: 'Sampling fidelity',
    kind: 'select',
    value: 'normal',
    options: [
      { label: 'Draft (coarse, small)', value: 'draft' },
      { label: 'Normal', value: 'normal' },
      { label: 'Fine (smooth, large)', value: 'fine' },
    ],
    note: 'How often a line is measured and how closely its edges are kept. Fine makes the cleanest tapers and the largest path.',
  },
  {
    ...PRINT,
    id: 'owl.engraved.seed',
    label: 'Seed',
    kind: 'int',
    value: 7,
    min: 0,
    max: 999,
    step: 1,
    note: 'The one seed behind the grain, the wobble and the scan’s noise. The same seed always draws the same owl.',
  },

  {
    ...SMALL,
    id: 'owl.engraved.adapt',
    label: 'Adapt to size',
    kind: 'boolean',
    value: true,
    note: 'Measure how many device pixels the owl is drawn across and coarsen the screen so a line is never finer than a pixel can hold.',
  },
  {
    ...SMALL,
    id: 'owl.engraved.minPitchPx',
    label: 'Smallest spacing',
    kind: 'number',
    value: 3.2,
    min: 1.5,
    max: 8,
    step: 0.1,
    note: 'Device pixels between lines, at the finest. Below it the screen is widened, the cross-hatch drops out, and the keyline holds at one pixel.',
  },

  {
    ...SCAN,
    id: 'owl.engraved.scan',
    label: 'Scan finish',
    kind: 'boolean',
    value: false,
    note: 'Run the whole figure through a filter that makes it look photocopied. Off, the plate is printed clean.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanSpread',
    label: 'Ink spread',
    kind: 'number',
    value: 0.2,
    min: 0,
    max: 0.9,
    step: 0.01,
    note: 'Blur before the clip: lines swell and corners round, figure units.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanWobble',
    label: 'Edge wobble',
    kind: 'number',
    value: 0.45,
    min: 0,
    max: 1.6,
    step: 0.01,
    note: 'How far a warp shoves an edge sideways, figure units.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanWobbleScale',
    label: 'Wobble grain',
    kind: 'number',
    value: 0.2,
    min: 0.03,
    max: 0.8,
    step: 0.01,
    note: 'Frequency of the warp. Low is a slow drift; high is a ragged edge.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanThreshold',
    label: '1-bit threshold',
    kind: 'number',
    value: 0.5,
    min: 0.15,
    max: 0.85,
    step: 0.01,
    note: 'Where grey goes to ink or to paper. Lower thins and breaks the lines; higher fattens them.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanHardness',
    label: '1-bit hardness',
    kind: 'number',
    value: 0.7,
    min: 0,
    max: 1,
    step: 0.01,
    note: '0 keeps the soft grey edge; 1 clips to pure ink and paper, the photocopier’s look.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanSpeckle',
    label: 'Speckle',
    kind: 'number',
    value: 0.25,
    min: 0,
    max: 1,
    step: 0.01,
    note: 'Specks of toner on the paper.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanDropout',
    label: 'Dropout',
    kind: 'number',
    value: 0.2,
    min: 0,
    max: 1,
    step: 0.01,
    note: 'Specks missing from the ink, where a line did not take.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanGenerations',
    label: 'Generations',
    kind: 'int',
    value: 1,
    min: 1,
    max: 4,
    step: 1,
    note: 'How many times the page has been copied. Each pass spreads, clips and roughens the last.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanSkew',
    label: 'Skew',
    kind: 'number',
    value: 0,
    min: -6,
    max: 6,
    step: 0.1,
    note: 'Degrees. The figure turns a little, as on a page fed in crooked.',
  },
  {
    ...SCAN,
    id: 'owl.engraved.scanPaperTone',
    label: 'Scanned paper',
    kind: 'color',
    value: '#ece3cc',
    note: 'The paper as the scanner saw it: the ground disc and lenses take this colour when the scan is on.',
  },
])
