/**
 * RAGtime Terms of Service — canonical text, kept in-repo so it's version-
 * controlled and rendered by the in-app /terms page (TermsOfService.tsx).
 * Companion to the Privacy Policy (privacy-policy-content.ts).
 *
 * Source of truth: signed off by counsel (Scott Anderson) + Ben, 2026-06-08
 * (Google Doc "RAGtime-Terms-of-Service_DRAFT-2026-06-07_sra comments").
 * Substantive wording is verbatim from that doc. Publication cleanups applied
 * to the residual drafting scaffolding only: removed the "DISCUSSION DRAFT —
 * not published" header + the [FOR SCOTT] preamble; the [DATE]/Provider line is
 * rendered from LAST_UPDATED in the page header; the §16 venue clause was
 * de-bracketed (DC courts, matching the §16 governing-law choice).
 *
 * When the terms change, edit this file and bump LAST_UPDATED; the deploy
 * publishes it. Keep in sync with the canonical doc.
 */

export const LAST_UPDATED = 'June 9, 2026'

export const TERMS_OF_SERVICE_MD = `
## 1. Acceptance of these terms

These Terms of Service (the "Terms") govern your use of RAGtime, a research tool provided by The Lawfare Institute. By accessing or using RAGtime, you agree to these Terms and to our Privacy Policy. If you do not agree, do not use RAGtime.

Two points are central, and by using RAGtime you specifically acknowledge and agree to them:

**AI-generated output contains errors.** Any answer, summary, generated search, or analysis produced using RAGtime's AI features may be inaccurate, incomplete, out of date, or fabricated. You will not rely on it without independently verifying it against the underlying source records.

**Lawfare is not the publisher of any AI output produced by RAGtime.** The material and analysis produced by the AI features are generated by third-party artificial-intelligence companies (such as Anthropic, OpenAI, or Google) and delivered to you through the RAGtime service. Lawfare does not author, endorse, adopt, or publish that output, and is not its source.

## 2. What RAGtime is

RAGtime is a tool for searching and analyzing collections of public-interest records — for example, federal court litigation documents, Department of Justice Office of Legal Counsel opinions, and State Department historical records, with more added over time. It offers structured search and filtering over those records, and optional AI features that can answer questions about, generate searches over, and summarize or analyze the records. It also enabled structured searches and querying of Lawfare itself.

RAGtime is a research-enabling tool. It helps you find and work with primary-source material; it is not a substitute for your own research, judgment, or professional advice.

## 3. AI features contain errors, and Lawfare is not the publisher of AI-generated material

When you use an AI feature on RAGtime, your query and the relevant records are sent to a third-party AI provider, which generates a response that is returned to you. Depending on your mode, that provider is Anthropic (paid mode) or the provider whose API key you supplied (bring-your-own-key mode).

**AI output contains errors.** Large language models can produce statements that are wrong, incomplete, outdated, or entirely fabricated, including invented citations or mischaracterizations of the records. You acknowledge this and agree that you are responsible for independently verifying any AI output against the underlying source documents before relying on or further using it. RAGtime surfaces the records behind each result precisely so that you can check them.

**Lawfare is not the publisher or author of AI output.** The material and analysis returned by the AI features are produced by the third-party AI companies that operate the models, not by Lawfare. Lawfare provides the means to query those models over the records; it does not write, review, endorse, adopt, or publish their output, and the output is not Lawfare analysis or a Lawfare publication. Only the Lawfare data corpus within RAGtime constitutes material published by Lawfare. Your use of AI providers' models is also subject to their own terms (see Section 10).

**Not professional advice.** Nothing produced by or through RAGtime is legal, financial, tax, medical, or other professional advice. Using RAGtime does not create an attorney-client relationship or any other professional or fiduciary relationship with Lawfare. For advice about a specific matter, consult a qualified professional.

## 4. Eligibility

RAGtime is intended for adult researchers. By using it you represent that you are at least 18 years of age, or that you are using it with the involvement and consent of a parent or legal guardian who agrees to these Terms on your behalf.

## 5. Accounts and access modes

RAGtime offers three ways to use it, and your obligations differ by mode:

**Local search (no account).** You can search and filter the records without an account or any AI features.

**Bring your own API key.** You supply an API key from an AI provider you have your own account with (Anthropic, OpenAI, or Google). AI calls are made under your account and that provider's terms; charges for that usage are between you and that provider. You are responsible for keeping your key confidential and for all activity under it.

**Sign in with Lawfare (paid).** You sign in with a passwordless "magic link" sent to your email, and use AI features billed by Lawfare against prepaid credit (Section 6). You are responsible for maintaining access to the email associated with your account and for activity conducted through your account.

You agree to provide accurate information, to use RAGtime only for lawful purposes, and not to share, sell, or transfer your account or access.

## 6. Payments, prepaid credit, and refunds (paid mode)

If you use the paid mode, the following apply:

**Prepaid credit.** You purchase credit in fixed prepaid blocks, processed by our payment provider, Stripe. The available amounts and any applicable details are shown at the time of purchase. Card payments are handled by Stripe; we never receive or store your full card number.

**How charges work.** Each AI query draws down your prepaid balance. The charge for a query is computed from the AI provider's usage-based price for that query (which depends on the model used and the number of tokens processed) plus a service margin, and is recorded in your transaction ledger. For most AI queries, an estimated cost and plan are shown before the query runs.

**Per-query cap and balance.** A per-query spending limit caps the maximum charge for any single query. A small courtesy buffer may allow a query to complete when your balance is near zero; once your balance falls below that buffer, new paid queries are paused until you add credit.

**Pricing changes.** We may change prices and the service margin prospectively. Changes do not affect credit you have already purchased.

Prepaid credit is non-refundable except where and as required by law; unused balances are not redeemable for cash. Please direct inquiries or payment disputes to lawfarewebevents@lawfaremedia.org.

## 7. Acceptable use

You agree not to:

- use RAGtime in violation of any law, or to infringe, defame, harass, or harm others;
- attempt to gain unauthorized access to the service, other users' accounts or data, or our systems; or probe, scan, or test the vulnerability of the service except as we expressly authorize;
- interfere with or disrupt the service, evade rate limits or usage controls, or place an unreasonable load on the infrastructure (including automated scraping or bulk extraction beyond the service's intended use);
- reverse engineer, decompile, or attempt to derive source code, except to the extent that restriction is prohibited by law;
- misrepresent AI output as Lawfare's analysis or publication, or otherwise attribute AI-generated material to Lawfare; or
- resell or commercially redistribute the service or paid AI access without our written permission.

We may suspend or limit access to protect the service, other users, or Lawfare, including to enforce rate limits or address abuse.

## 8. The records in RAGtime

The collections RAGtime makes searchable are public records obtained from government and other publicly available sources — along with materials published by Lawfare itself. We assemble public materials to be a broad and useful research resource. We do not warrant that the collections are complete, accurate, current, or free of errors; the corpus is deliberately over-inclusive in places and may also be missing material, and source records may themselves contain errors.

These records may contain personal information about third parties as published in the public record. That content is part of the source material; how we handle it, and requests concerning it, are addressed in the Privacy Policy.

## 9. Intellectual property

The source records are generally government works or otherwise public records, and Lawfare claims no ownership of the underlying public records themselves. The RAGtime service — including its software, design, organization and compilation of the collections, and interface — is owned by Lawfare or its licensors and is protected by applicable law. "The Lawfare Institute," "Lawfare," and "RAGtime" and related names and logos are marks of Lawfare; these Terms do not grant you any right to use them.

Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to use RAGtime for your own research. You retain whatever rights you have in the queries you submit; you grant us permission to process them as needed to operate the service, as described in the Privacy Policy.

## 10. Third-party services

RAGtime relies on third parties to operate, including Stripe (payments), the AI providers (Anthropic in paid mode; Anthropic, OpenAI, or Google in bring-your-own-key mode), Supabase, Cloudflare, and GitHub Pages. Your use of features that depend on a third party is also subject to that party's terms and policies. In bring-your-own-key mode in particular, your relationship for the AI service is with the provider you chose, and we are not responsible for that provider's acts, omissions, output, charges, or data practices.

## 11. Beta service; availability and changes

RAGtime is offered on an evolving basis and, during the beta period, is provided for limited testing. Features may change, be added, or be removed, and the service may be unavailable, interrupted, or discontinued at any time without notice. We do not guarantee any particular level of availability, performance, or data retention.

## 12. Disclaimer of warranties

RAGtime, including all records and AI features, is provided "as is" and "as available," without warranties of any kind, whether express, implied, or statutory, including any implied warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement. Without limiting Sections 3 and 8, we do not warrant that the service or any output will be accurate, complete, reliable, current, secure, or error-free, or that the records are complete or authoritative.

## 13. Limitation of liability

To the maximum extent permitted by law, Lawfare and its officers, directors, employees, and contractors will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, data, goodwill, or other intangible losses, arising out of or relating to your use of (or inability to use) RAGtime or any reliance on its output, even if advised of the possibility of such damages.

To the maximum extent permitted by law, Lawfare's total liability for all claims relating to RAGtime will not exceed the greater of the amount you paid Lawfare for the service in the twelve months preceding the event giving rise to the claim, or U.S. $100.

## 14. Indemnification

You agree to indemnify and hold harmless Lawfare and its officers, directors, employees, and contractors from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising out of your use of RAGtime, your violation of these Terms, or your violation of any law or the rights of any third party, including any misuse or misattribution of AI output.

## 15. Termination

You may stop using RAGtime at any time. We may suspend or terminate your access, with or without notice, if you violate these Terms, if needed to protect the service or others, if we discontinue the service, or for any other reason permitted by law. Provisions that by their nature should survive termination — including Sections 3, 8, 9, and 12 through 16 — will survive.

## 16. Governing law and disputes

These Terms are governed by the laws of the District of Columbia, without regard to its conflict-of-laws rules. The state and federal courts located in the District of Columbia will have jurisdiction over any dispute that is not otherwise resolved, and you consent to their jurisdiction and venue.

## 17. Changes to these terms

We may update these Terms from time to time. We will post the updated Terms here and update the "last updated" date. Material changes will take effect as stated in the notice; your continued use after the effective date means you accept the updated Terms.

## 18. Contact

Questions about these Terms: lawfarewebevents@lawfaremedia.org
`
