/**
 * RAGtime Terms of Service — canonical text, kept in-repo so it's version-
 * controlled and rendered by the in-app /terms page (TermsOfService.tsx).
 * Companion to the Privacy Policy (privacy-policy-content.ts).
 *
 * Source of truth: signed off by counsel (Scott Anderson) + Ben, 2026-06-08
 * (Google Doc "RAGtime-Terms-of-Service_DRAFT-2026-06-07_sra comments").
 * Substantive wording is verbatim from that doc. Publication cleanups applied
 * to the residual drafting scaffolding only: removed the "DISCUSSION DRAFT —
 * not published" header + the [FOR SCOTT] preamble; the [DATE]/Provider line is
 * rendered from LAST_UPDATED in the page header; the §16 venue clause was
 * de-bracketed (DC courts, matching the §16 governing-law choice).
 *
 * Updated 2026-10-04: Google sign-in and organisation accounts (§5, §6), a
 * connected AI assistant (§5), saved items as a planned feature (§9, consent
 * asked again at launch), and an "In plain terms" reading under every section.
 * Counsel's wording is kept wherever the facts did not change.
 *
 * When the terms change, edit this file and bump LAST_UPDATED; the deploy
 * publishes it. Keep in sync with the canonical doc.
 */

export const LAST_UPDATED = 'October 4, 2026'

export const TERMS_OF_SERVICE_MD = `
## How to read this page

Terms of service are a contract, and contracts are written to be exact rather than friendly. RAGtime is a tool for reading exactly this kind of text, so we have done to our own terms what the tool does to the law: every section is followed by the same section in plain terms. The plain reading is a guide to the contract, not a replacement for it; where they differ, the contract governs, and we would like to hear about it so we can close the gap.

## 1. Acceptance of these terms

These Terms of Service (the "Terms") govern your use of RAGtime, a research tool provided by The Lawfare Institute. By accessing or using RAGtime, you agree to these Terms and to our Privacy Policy. If you do not agree, do not use RAGtime.

Two points are central, and by using RAGtime you specifically acknowledge and agree to them:

**AI-generated output contains errors.** Any answer, summary, generated search, or analysis produced using RAGtime's AI features may be inaccurate, incomplete, out of date, or fabricated. You will not rely on it without independently verifying it against the underlying source records.

**Lawfare is not the publisher of any AI output produced by RAGtime.** The material and analysis produced by the AI features are generated by third-party artificial-intelligence companies (such as Anthropic, OpenAI, or Google) and delivered to you through the RAGtime service. Lawfare does not author, endorse, adopt, or publish that output, and is not its source.

> **In plain terms.** Using RAGtime means agreeing to these terms. The two that matter most: the AI gets things wrong, so check the documents; and when it does get things wrong, that is the AI company's text, not Lawfare's.

## 2. What RAGtime is

RAGtime is a tool for searching and analyzing collections of public-interest records — for example, federal court litigation documents, Department of Justice Office of Legal Counsel opinions, and State Department historical records, with more added over time. It offers structured search and filtering over those records, and optional AI features that can answer questions about, generate searches over, and summarize or analyze the records. It also enabled structured searches and querying of Lawfare itself.

RAGtime is a research-enabling tool. It helps you find and work with primary-source material; it is not a substitute for your own research, judgment, or professional advice.

> **In plain terms.** RAGtime helps you find and read primary sources. It does not do your thinking for you.

## 3. AI features contain errors, and Lawfare is not the publisher of AI-generated material

When you use an AI feature on RAGtime, your query and the relevant records are sent to a third-party AI provider, which generates a response that is returned to you. Depending on your mode, that provider is Anthropic (paid mode) or the provider whose API key you supplied (bring-your-own-key mode).

**AI output contains errors.** Large language models can produce statements that are wrong, incomplete, outdated, or entirely fabricated, including invented citations or mischaracterizations of the records. You acknowledge this and agree that you are responsible for independently verifying any AI output against the underlying source documents before relying on or further using it. RAGtime surfaces the records behind each result precisely so that you can check them.

**Lawfare is not the publisher or author of AI output.** The material and analysis returned by the AI features are produced by the third-party AI companies that operate the models, not by Lawfare. Lawfare provides the means to query those models over the records; it does not write, review, endorse, adopt, or publish their output, and the output is not Lawfare analysis or a Lawfare publication. Only the Lawfare data corpus within RAGtime constitutes material published by Lawfare. Your use of AI providers' models is also subject to their own terms (see Section 11).

**Not professional advice.** Nothing produced by or through RAGtime is legal, financial, tax, medical, or other professional advice. Using RAGtime does not create an attorney-client relationship or any other professional or fiduciary relationship with Lawfare. For advice about a specific matter, consult a qualified professional.

> **In plain terms.** The AI can invent a citation that does not exist. Every result shows you the documents behind it so you can check — and you must. Nothing here is legal advice, and reading it does not make Lawfare your lawyer.

## 4. Eligibility

RAGtime is intended for adult researchers. By using it you represent that you are at least 18 years of age, or that you are using it with the involvement and consent of a parent or legal guardian who agrees to these Terms on your behalf.

> **In plain terms.** You are an adult, or an adult who has read this is with you.

## 5. Accounts and access modes

RAGtime offers three ways to use it, and your obligations differ by mode:

**Local search (no account).** You can search and filter the records without an account or any AI features.

**Bring your own API key.** You supply an API key from an AI provider you have your own account with (Anthropic, OpenAI, or Google). AI calls are made under your account and that provider's terms; charges for that usage are between you and that provider. You are responsible for keeping your key confidential and for all activity under it.

**Sign in with Lawfare (paid).** You sign in with a passwordless "magic link" sent to your email or with your Google account, and use AI features billed by Lawfare against prepaid credit (Section 6). You are responsible for maintaining access to the email or Google account associated with your account and for activity conducted through your account.

**Organisation accounts.** An organisation on RAGtime (today, Lawfare for its own staff) may admit its members, pay for their AI use from its own allowance, and require them to sign in with Google. If your account is a member of an organisation, the organisation may end that membership at any time; your account then continues as an ordinary paid account, and anything you shared with the organisation stays with the organisation. Lawfare addresses (lawfaremedia.org) sign in with Google only.

**Connecting an AI assistant.** You may authorise an AI assistant you use (such as Claude) to act on RAGtime as you. You do so on a page we show you that names the assistant; approving it is your decision and your responsibility. Everything the assistant does under that authorisation — searches, questions, charges — is done by you under these Terms. You may revoke the authorisation from the assistant's own settings at any time. Your relationship with the assistant is governed by its provider's terms, not ours.

You agree to provide accurate information, to use RAGtime only for lawful purposes, and not to share, sell, or transfer your account or access.

> **In plain terms.** No account, your own AI key, or sign in with us — by an emailed link or with Google. Lawfare staff must use Google, and Lawfare pays for them. If you let an assistant like Claude use RAGtime as you, what it does counts as you doing it, and you can switch it off whenever you like.

## 6. Payments, prepaid credit, and refunds (paid mode)

If you use the paid mode, the following apply:

**Prepaid credit.** You purchase credit in fixed prepaid blocks, processed by our payment provider, Stripe. The available amounts and any applicable details are shown at the time of purchase. Card payments are handled by Stripe; we never receive or store your full card number.

**How charges work.** Each AI query draws down your prepaid balance. The charge for a query is computed from the AI provider's usage-based price for that query (which depends on the model used and the number of tokens processed) plus a service margin, and is recorded in your transaction ledger. For most AI queries, an estimated cost and plan are shown before the query runs.

**Per-query cap and balance.** A per-query spending limit caps the maximum charge for any single query. A small courtesy buffer may allow a query to complete when your balance is near zero; once your balance falls below that buffer, new paid queries are paused until you add credit.

**Accounts paid by an organisation.** While your account is a member of an organisation that pays for it, your AI queries draw on the organisation's daily allowance instead of a personal balance, and no charge is recorded against you. The organisation's allowance may run out for the day; when it does, queries are paused until it resets. If your membership ends, the paid-mode rules above apply to your account from then on.

**Pricing changes.** We may change prices and the service margin prospectively. Changes do not affect credit you have already purchased.

Prepaid credit is non-refundable except where and as required by law; unused balances are not redeemable for cash. Please direct inquiries or payment disputes to lawfarewebevents@lawfaremedia.org.

> **In plain terms.** You buy credit up front; each AI question costs what the AI company charges us plus a margin, and you see an estimate first. There is a cap per question so one query cannot drain you. If your organisation pays, nothing is charged to you and the organisation's daily allowance is the limit. Credit is not refunded.

## 7. Acceptable use

You agree not to:

- use RAGtime in violation of any law, or to infringe, defame, harass, or harm others;
- attempt to gain unauthorized access to the service, other users' accounts or data, or our systems; or probe, scan, or test the vulnerability of the service except as we expressly authorize;
- interfere with or disrupt the service, evade rate limits or usage controls, or place an unreasonable load on the infrastructure (including automated scraping or bulk extraction beyond the service's intended use);
- reverse engineer, decompile, or attempt to derive source code, except to the extent that restriction is prohibited by law;
- misrepresent AI output as Lawfare's analysis or publication, or otherwise attribute AI-generated material to Lawfare; or
- resell or commercially redistribute the service or paid AI access without our written permission.

We may suspend or limit access to protect the service, other users, or Lawfare, including to enforce rate limits or address abuse.

> **In plain terms.** Do not break the law with it, break into it, overload it, or pass the AI's words off as Lawfare's. If someone does, we can cut them off.

## 8. The records in RAGtime

The collections RAGtime makes searchable are public records obtained from government and other publicly available sources — along with materials published by Lawfare itself. We assemble public materials to be a broad and useful research resource. We do not warrant that the collections are complete, accurate, current, or free of errors; the corpus is deliberately over-inclusive in places and may also be missing material, and source records may themselves contain errors.

These records may contain personal information about third parties as published in the public record. That content is part of the source material; how we handle it, and requests concerning it, are addressed in the Privacy Policy.

> **In plain terms.** The documents are public records we gathered. Some things are missing, some are in by mistake, and the originals have their own errors. Treat the collection as a starting point, not a complete one.

## 9. Saved items (planned, not yet on)

We intend to let signed-in people save records and citations into lists, private to them or shared with their organisation. This feature does not exist yet. When it does, it will be off until you turn it on, and you will be asked for your permission inside the feature before anything is kept. The following will apply to it:

- What you save is yours. You keep whatever rights you have in it, and you grant us permission to store it and show it back to you and to anyone you share it with.
- A list shared with an organisation is visible to that organisation's members, who may add to it; it stays with the organisation if your membership ends.
- We may remove saved content that violates Section 7, and saved items are deleted with your account.
- Saved items are a convenience, not an archive. Keep your own copy of anything you cannot afford to lose (Section 12).

> **In plain terms.** Soon you will be able to keep lists of documents, for yourself or for your team. It is not built yet; when it is, it will ask you first. Your lists are yours, your team's lists stay with the team, and we do not promise to be your backup.

## 10. Intellectual property

The source records are generally government works or otherwise public records, and Lawfare claims no ownership of the underlying public records themselves. The RAGtime service — including its software, design, organization and compilation of the collections, and interface — is owned by Lawfare or its licensors and is protected by applicable law. "The Lawfare Institute," "Lawfare," and "RAGtime" and related names and logos are marks of Lawfare; these Terms do not grant you any right to use them.

Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to use RAGtime for your own research. You retain whatever rights you have in the queries you submit; you grant us permission to process them as needed to operate the service, as described in the Privacy Policy.

> **In plain terms.** The public records belong to nobody; the tool belongs to Lawfare. You may use it for your research, and your questions stay yours.

## 11. Third-party services

RAGtime relies on third parties to operate, including Stripe (payments), the AI providers (Anthropic in paid mode; Anthropic, OpenAI, or Google in bring-your-own-key mode), Google (sign-in, if you choose it), Resend (sign-in email delivery), Supabase, Cloudflare, and GitHub Pages. Your use of features that depend on a third party is also subject to that party's terms and policies. In bring-your-own-key mode in particular, your relationship for the AI service is with the provider you chose, and we are not responsible for that provider's acts, omissions, output, charges, or data practices. The same is true of an AI assistant you connect under Section 5.

> **In plain terms.** Other companies run parts of this. When you use their part, their rules apply too, and we cannot answer for them.

## 12. Beta service; availability and changes

RAGtime is offered on an evolving basis and, during the beta period, is provided for limited testing. Features may change, be added, or be removed, and the service may be unavailable, interrupted, or discontinued at any time without notice. We do not guarantee any particular level of availability, performance, or data retention.

> **In plain terms.** This is a beta. It can change or go down without warning, and we do not promise to keep anything.

## 13. Disclaimer of warranties

RAGtime, including all records and AI features, is provided "as is" and "as available," without warranties of any kind, whether express, implied, or statutory, including any implied warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement. Without limiting Sections 3 and 8, we do not warrant that the service or any output will be accurate, complete, reliable, current, secure, or error-free, or that the records are complete or authoritative.

> **In plain terms.** We make no guarantees about the service, the records, or the AI's output. "As is" means exactly that.

## 14. Limitation of liability

To the maximum extent permitted by law, Lawfare and its officers, directors, employees, and contractors will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, data, goodwill, or other intangible losses, arising out of or relating to your use of (or inability to use) RAGtime or any reliance on its output, even if advised of the possibility of such damages.

To the maximum extent permitted by law, Lawfare's total liability for all claims relating to RAGtime will not exceed the greater of the amount you paid Lawfare for the service in the twelve months preceding the event giving rise to the claim, or U.S. $100.

> **In plain terms.** If using RAGtime costs you something, the most Lawfare would owe you is what you paid us in the past year, or $100, whichever is more — and nothing for indirect losses. Where the law does not allow such a limit, the law wins.

## 15. Indemnification

You agree to indemnify and hold harmless Lawfare and its officers, directors, employees, and contractors from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising out of your use of RAGtime, your violation of these Terms, or your violation of any law or the rights of any third party, including any misuse or misattribution of AI output.

> **In plain terms.** If your use of RAGtime gets Lawfare sued — you broke these terms, broke the law, or passed the AI's words off as Lawfare's — you cover the cost.

## 16. Termination

You may stop using RAGtime at any time. We may suspend or terminate your access, with or without notice, if you violate these Terms, if needed to protect the service or others, if we discontinue the service, or for any other reason permitted by law. Provisions that by their nature should survive termination — including Sections 3, 8, 10, and 13 through 17 — will survive.

> **In plain terms.** You can leave whenever you want. We can close your access if you break the rules or if we shut the service down. The disclaimers and limits above outlast the account.

## 17. Governing law and disputes

These Terms are governed by the laws of the District of Columbia, without regard to its conflict-of-laws rules. The state and federal courts located in the District of Columbia will have jurisdiction over any dispute that is not otherwise resolved, and you consent to their jurisdiction and venue.

> **In plain terms.** D.C. law applies, and a dispute goes to a court in D.C.

## 18. Changes to these terms

We may update these Terms from time to time. We will post the updated Terms here and update the "last updated" date. Material changes will take effect as stated in the notice; your continued use after the effective date means you accept the updated Terms.

> **In plain terms.** When the terms change, the date at the top changes. Keep using RAGtime after a change and you have accepted it.

## 19. Contact

Questions about these Terms: lawfarewebevents@lawfaremedia.org

> **In plain terms.** Write to us.
`
