/* GENERATED by app/scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * @font-face rules for the PDF export's print window. That window is opened
 * with window.open(''), so it is an about:blank document: it inherits this
 * page's Content-Security-Policy, which is why it cannot fetch Google Fonts
 * once the policy is enforced, and it inherits no base URL, which is why these
 * URLs are made absolute rather than left root-relative.
 */
import f0 from '../assets/fonts/eb-garamond-italic-latin-ext-var.woff2'
import f1 from '../assets/fonts/eb-garamond-italic-latin-var.woff2'
import f2 from '../assets/fonts/eb-garamond-normal-latin-ext-var.woff2'
import f3 from '../assets/fonts/eb-garamond-normal-latin-var.woff2'
import f4 from '../assets/fonts/lato-italic-latin-ext-400.woff2'
import f5 from '../assets/fonts/lato-italic-latin-400.woff2'
import f6 from '../assets/fonts/lato-normal-latin-ext-400.woff2'
import f7 from '../assets/fonts/lato-normal-latin-400.woff2'
import f8 from '../assets/fonts/lato-normal-latin-ext-700.woff2'
import f9 from '../assets/fonts/lato-normal-latin-700.woff2'

type Face = {
  family: string
  style: string
  weight: string
  url: string
  range: string
}

const FACES: Face[] = [
  { family: 'EB Garamond', style: 'italic', weight: '400', url: f0, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'EB Garamond', style: 'italic', weight: '400', url: f1, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'EB Garamond', style: 'italic', weight: '600', url: f0, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'EB Garamond', style: 'italic', weight: '600', url: f1, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'EB Garamond', style: 'normal', weight: '400', url: f2, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'EB Garamond', style: 'normal', weight: '400', url: f3, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'EB Garamond', style: 'normal', weight: '600', url: f2, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'EB Garamond', style: 'normal', weight: '600', url: f3, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'EB Garamond', style: 'normal', weight: '700', url: f2, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'EB Garamond', style: 'normal', weight: '700', url: f3, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'Lato', style: 'italic', weight: '400', url: f4, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'Lato', style: 'italic', weight: '400', url: f5, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'Lato', style: 'normal', weight: '400', url: f6, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'Lato', style: 'normal', weight: '400', url: f7, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
  { family: 'Lato', style: 'normal', weight: '700', url: f8, range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF' },
  { family: 'Lato', style: 'normal', weight: '700', url: f9, range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD' },
]

/** @font-face block for the print document, with origin-absolute font URLs. */
export function printFontFaceCss(): string {
  return FACES.map(
    (f) =>
      `@font-face { font-family: '${f.family}'; font-style: ${f.style}; font-weight: ${f.weight}; font-display: swap; src: url('${new URL(f.url, location.origin).href}') format('woff2'); unicode-range: ${f.range}; }`
  ).join('\n')
}
